### ISSUE TITLE
Purpose using first convolution

### ISSUE THREAD

**Issue by John1231983** [liuzhuang13/DenseNet#29]
In your network architecture for CIFAR and imagenet dataset, what does purpose use the first convolution (before pooling-denseblock1)? In the imagenet, you use two convolutions block before entering the dense-block, while CIFAR just one, any reason? Thanks

**Comment by liuzhuang13** [comment]
Hi @John1231983  We follow ResNet's design on both datasets. https://github.com/facebook/fb.resnet.torch

**Comment by John1231983** [comment]
Thanks. I knew it. In your opinion, do you have any explanation?

**Comment by liuzhuang13** [comment]
In ImageNet we need to downsample the image twice (so that the image becomes of 56x56 size) before entering the first dense block, this is through one stride convolution and one max pooling.

In CIFAR dataset, the input image and the first dense block feature maps are of the same size (32x32), the first convolution is just a conventional design so that we don't include raw input image in the first dense block.
